# 12ToneGOL
## 12-tone matrix + Game of Life Music Generator
### By Peñas

In [1]:
import numpy as np
from IPython.display import clear_output
import time

tablero = np.zeros(shape = (12, 12), dtype=int)
op = [(0, 1), (1, 0), (1, 1), (-1, 1)]

notas = ['C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'G#', 'A', 'Bb', 'B']

orden = [3, 6, 8, 4, 1, 5, 0, 2, 10, 11, 9, 7]
prima_cero = [notas[i] for i in orden]
secuencia = []

for j in range(0,12):
    secuencia.append([prima_cero[(i+j) % 12] for i in orden])
    
secuencia = np.array(secuencia)
    
vivos_iniciales = [(0,3), (0,4), (0,5), (1,0), (1,1), (1,5), (2,0), (2,1), (2,2), (2,3), (2,4), (4,0), (4,1), (4,2), (4,3), (4,4), (5,0), (5,1), (5,5), (6,3), (6,4), (6,5)]

for i in vivos_iniciales:
    tablero[i] = 1
    
print (secuencia)
print(tablero)

[['E' 'C' 'Bb' 'C#' 'F#' 'F' 'Eb' 'G#' 'A' 'G' 'B' 'D']
 ['C#' 'D' 'B' 'F' 'G#' 'C' 'F#' 'E' 'G' 'Eb' 'A' 'Bb']
 ['F' 'Bb' 'A' 'C' 'E' 'D' 'G#' 'C#' 'Eb' 'F#' 'G' 'B']
 ['C' 'B' 'G' 'D' 'C#' 'Bb' 'E' 'F' 'F#' 'G#' 'Eb' 'A']
 ['D' 'A' 'Eb' 'Bb' 'F' 'B' 'C#' 'C' 'G#' 'E' 'F#' 'G']
 ['Bb' 'G' 'F#' 'B' 'C' 'A' 'F' 'D' 'E' 'C#' 'G#' 'Eb']
 ['B' 'Eb' 'G#' 'A' 'D' 'G' 'C' 'Bb' 'C#' 'F' 'E' 'F#']
 ['A' 'F#' 'E' 'G' 'Bb' 'Eb' 'D' 'B' 'F' 'C' 'C#' 'G#']
 ['G' 'G#' 'C#' 'Eb' 'B' 'F#' 'Bb' 'A' 'C' 'D' 'F' 'E']
 ['Eb' 'E' 'F' 'F#' 'A' 'G#' 'B' 'G' 'D' 'Bb' 'C' 'C#']
 ['F#' 'C#' 'C' 'G#' 'G' 'E' 'A' 'Eb' 'Bb' 'B' 'D' 'F']
 ['G#' 'F' 'D' 'E' 'Eb' 'C#' 'G' 'F#' 'B' 'A' 'Bb' 'C']]
[[0 0 0 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [2]:
prev = tablero.copy()
total_vecinos = np.zeros_like(tablero)
musica = np.zeros(shape = tablero.shape, dtype = str)

linea = []
lineas = []

generaciones = 0


print(tablero, end = ' ', flush=True)
clear_output(wait=True)

while True:
    for i in range (0, len(tablero)):
        for j in range (0, len(tablero)):
            
            casillas_vecinas = []
            vecinos_vivos = 0
            
            
            for a in op:
                casillas_vecinas.append(list(map(sum, zip([i, j], a))))
                casillas_vecinas.append(list(map(sum, zip([i, j], [-x for x in a]))))

            for m, n in casillas_vecinas:
                try:
                    if tablero[m][n] == 1:
                        vecinos_vivos +=1
                except IndexError:
                    pass
                
            total_vecinos[i][j] = vecinos_vivos

    for i in range (0, len(tablero)):
        for j in range (0, len(tablero)):
            if prev[i][j] == 1:
                if total_vecinos[i][j] < 2 or total_vecinos[i][j] > 3:
                    tablero[i][j] = 0
                elif total_vecinos[i][j] == 2 or total_vecinos[i][j] == 3:
                    tablero[i][j] = 1
            elif prev[i][j] == 0:
                if total_vecinos[i][j] == 3:
                    tablero[i][j] = 1
            
            if tablero[i][j] == 1:
                linea.append(str(secuencia[i][j]))
                
    musica = np.core.defchararray.multiply(secuencia, tablero)        
#     print(linea)
    lineas.append(linea)
    linea = []
    print(musica, generaciones)
    clear_output(wait=True)
    if np.array_equal(tablero, prev):
        break
        
    generaciones += 1
    prev = tablero.copy()
    
    time.sleep(0.1)

[['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']] 54


In [3]:
print ('Total generaciones = ' + str(generaciones))

for l in lineas:
    print(*l)

Total generaciones = 54
F# F C# C F A C E D Eb Bb F Bb A D G Bb
F# F D C Bb C E A Bb F G A D G Bb Eb
F# F B F C A E Eb F F# B A C Bb Eb
C# F# F B C A E Eb F F# B C A A C Eb
C# F# F B C C Eb F B F# A G# A C
C# F# F B C D C# Bb F B G F# A F G# A
C# F# F F C C E D Bb C# G A F Eb G# A
C# F B C A C D D Bb F C# G A F Eb G# E
F# B C F# A C D G# G D Bb E F C# G F# A F Eb G# F# E
F B F# Bb C# G F A F C G F# B A F B A F# E
F# Bb A G# C# B G E F F# A F B C Bb G B A F B A D F# E
F# E Bb A D Eb C D F# Bb F G# Bb G B F B A D G F# E G
F# E Bb A G# Eb B D F F# G# D A Bb F C Bb G B G F# E G C#
F# E Bb A G# F# D C# E G# Bb F C F# C B F# E G G# C# Eb
F# E A C G# Eb C# E F F# Eb C A G G# Eb F
F# E C Eb G Bb E F# Bb B C E G# Eb F
E D Eb G D Bb E F# F B C E G# Eb F
E D Eb D F# Bb F B C E G# Eb F
E D E F F# Bb F C E G# Eb F
C# D Bb F Bb F B C B C E G# Eb F
G# D Bb F F# Eb B B A A E G# Eb F
G# C# C# Bb F Eb Bb B F# B G# A D E G G# Eb F
D G# C# D C# Bb F Eb B C# G Eb D F# G# Eb F
F# D C# D F Eb Bb B C# G F# A 