# 12ToneGOL
## 12-tone matrix & Conway's Game of Life Music Generator
### *by xoss1*

In [1]:
import numpy as np
from IPython.display import clear_output
import time

tablero = np.zeros(shape = (12, 12), dtype=int)
op = [(0, 1), (1, 0), (1, 1), (-1, 1)]

notas = ['C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'G#', 'A', 'Bb', 'B']

orden = [3, 6, 8, 4, 1, 5, 0, 2, 10, 11, 9, 7]
prima_cero = [notas[i] for i in orden]
secuencia = []

for j in range(0,12):
    secuencia.append([prima_cero[(i+j) % 12] for i in orden])
    
secuencia = np.array(secuencia)
    
vivos_iniciales = [(5, 5), (4, 6), (4, 5), (5, 4),  (3,5)]

for i in vivos_iniciales:
    tablero[i] = 1
    
print (secuencia)
print(tablero)

[['E' 'C' 'Bb' 'C#' 'F#' 'F' 'Eb' 'G#' 'A' 'G' 'B' 'D']
 ['C#' 'D' 'B' 'F' 'G#' 'C' 'F#' 'E' 'G' 'Eb' 'A' 'Bb']
 ['F' 'Bb' 'A' 'C' 'E' 'D' 'G#' 'C#' 'Eb' 'F#' 'G' 'B']
 ['C' 'B' 'G' 'D' 'C#' 'Bb' 'E' 'F' 'F#' 'G#' 'Eb' 'A']
 ['D' 'A' 'Eb' 'Bb' 'F' 'B' 'C#' 'C' 'G#' 'E' 'F#' 'G']
 ['Bb' 'G' 'F#' 'B' 'C' 'A' 'F' 'D' 'E' 'C#' 'G#' 'Eb']
 ['B' 'Eb' 'G#' 'A' 'D' 'G' 'C' 'Bb' 'C#' 'F' 'E' 'F#']
 ['A' 'F#' 'E' 'G' 'Bb' 'Eb' 'D' 'B' 'F' 'C' 'C#' 'G#']
 ['G' 'G#' 'C#' 'Eb' 'B' 'F#' 'Bb' 'A' 'C' 'D' 'F' 'E']
 ['Eb' 'E' 'F' 'F#' 'A' 'G#' 'B' 'G' 'D' 'Bb' 'C' 'C#']
 ['F#' 'C#' 'C' 'G#' 'G' 'E' 'A' 'Eb' 'Bb' 'B' 'D' 'F']
 ['G#' 'F' 'D' 'E' 'Eb' 'C#' 'G' 'F#' 'B' 'A' 'Bb' 'C']]
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [2]:
prev = tablero.copy()
pre_prev = prev.copy()
total_vecinos = np.zeros_like(tablero)
musica = np.zeros(shape = tablero.shape, dtype = str)

linea = []
lineas = []

generaciones = 0


print(tablero, end = ' ', flush=True)
clear_output(wait=True)

while True:
    generaciones += 1
    
    for i in range (0, len(tablero)):
        for j in range (0, len(tablero)):
            
            casillas_vecinas = []
            vecinos_vivos = 0
            
            
            for a in op:
                casillas_vecinas.append(list(map(sum, zip([i, j], a))))
                casillas_vecinas.append(list(map(sum, zip([i, j], [-x for x in a]))))

            for m, n in casillas_vecinas:
                try:
                    if tablero[m][n] == 1:
                        vecinos_vivos +=1
                except IndexError:
                    pass
                
            total_vecinos[i][j] = vecinos_vivos

    for i in range (0, len(tablero)):
        for j in range (0, len(tablero)):
            if prev[i][j] == 1:
                if total_vecinos[i][j] < 2 or total_vecinos[i][j] > 3:
                    tablero[i][j] = 0
                elif total_vecinos[i][j] == 2 or total_vecinos[i][j] == 3:
                    tablero[i][j] = 1
            elif prev[i][j] == 0:
                if total_vecinos[i][j] == 3:
                    tablero[i][j] = 1
    
            
            
            if tablero[i][j] == 1:
                linea.append(str(secuencia[i][j]))
                
    musica = np.core.defchararray.multiply(secuencia, tablero)      
#     print(linea)
    lineas.append([generaciones, np.array(linea)])
    linea = []
    print(musica, generaciones)
    
    if np.array_equal(tablero, prev):
        print('FIN (Muerte)')
        break
    
    if np.array_equal (tablero, pre_prev):
        print('FIN (Estancamiento)')
        break
    
    
    pre_prev = prev.copy()
    prev = tablero.copy()
       
    clear_output(wait=True)
    
    time.sleep(0.1)

[['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['F' 'Bb' '' '' '' '' '' '' '' '' '' '']
 ['C' '' '' '' '' '' '' '' '' '' '' '']
 ['D' '' 'Eb' '' '' '' '' '' '' '' '' '']
 ['' 'G' 'F#' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '' '' '']] 91
FIN (Muerte)


In [3]:
print('Total generaciones = ' + str(generaciones))

for l in np.array(lineas):
    print(*l)

Total generaciones = 91
1 ['Bb' 'E' 'C#' 'C' 'A' 'F']
2 ['Bb' 'E' 'F' 'C' 'A' 'F' 'G']
3 ['Bb' 'E' 'F' 'C' 'C' 'A' 'F' 'G' 'C']
4 ['Bb' 'E' 'F' 'C' 'C' 'D' 'D' 'C']
5 ['Bb' 'E' 'F' 'C' 'B' 'C' 'F' 'D' 'G']
6 ['Bb' 'E' 'Bb' 'F' 'C' 'B' 'C' 'F' 'D' 'D' 'G' 'C']
7 ['C#' 'Bb' 'E' 'Bb' 'C' 'D' 'A' 'D' 'C' 'Bb' 'Eb']
8 ['D' 'C#' 'Bb' 'E' 'F' 'B' 'C' 'B' 'C' 'D' 'E' 'D' 'G' 'C' 'Bb' 'Bb' 'Eb'
 'D']
9 ['E' 'D' 'G#' 'C' 'G#' 'B' 'E' 'C#' 'Bb' 'B' 'F#']
10 ['C' 'D' 'Bb' 'E' 'F' 'C' 'G#' 'E' 'C#' 'Bb' 'C#']
11 ['E' 'D' 'Bb' 'F' 'F#' 'E' 'C#' 'Bb' 'C#' 'F']
12 ['E' 'D' 'G#' 'C#' 'Bb' 'E' 'F#' 'E' 'C#' 'G#' 'C#' 'F' 'F']
13 ['C' 'E' 'G#' 'C#' 'C#' 'E' 'F' 'B' 'G#' 'E' 'F#' 'G#' 'C#' 'E' 'F' 'C']
14 ['C' 'F#' 'E' 'C#' 'C#' 'G#' 'B' 'C#' 'C' 'G#' 'E' 'F#' 'E' 'G#' 'Eb' 'C#'
 'E' 'F' 'C']
15 ['C' 'F#' 'E' 'G#' 'C#' 'G#' 'Eb' 'B' 'C#' 'C' 'G' 'F' 'Eb' 'Bb' 'C#' 'E'
 'F#' 'F' 'C']
16 ['C' 'F#' 'E' 'G#' 'C#' 'F' 'Eb' 'B' 'C#' 'C' 'G' 'Bb' 'A' 'E' 'Eb' 'Bb'
 'C#' 'E' 'F#' 'B' 'F' 'C' 'C#']
17 ['C' 'F#' 'E